### ISSUE TITLE
Add prometheus metrics

### ISSUE THREAD

**Issue by joostjager** [NYDIG-OSS/lnmux#15]
Both for monitoring regular operation (number of htlcs settled, failed, etc) as well as certain error cases that are worth keeping an eye on. One of those is a mismatch of the rederived preimage and the payment hash.

**Comment by Torakushi** [comment]
In case of problem, it could be good to add some prometheus metrics for our grpc_server:

https://github.com/grpc-ecosystem/go-grpc-prometheus

**Comment by joostjager** [comment]
I think we already use that in lnmux?

**Comment by Torakushi** [comment]
I missed this sorry...

**Comment by Torakushi** [comment]
Coule be nice to have a gauge indicating how many LND nodes we are currently connected to (users can trigger alerts based on this)

**Comment by joostjager** [comment]
Do you think we should do a [0,1] metric for each node separately, identified by a label? Given the parallel nature of the node handling, it would require synchronization to bring things together to a single metric.

**Comment by joostjager** [comment]
I suppose it could work with increment and decrement too, if we don't allow any escape routes.

Maybe the metric 'disconnected_node_count' is better for alerting, because then we don't need to know how many nodes we have?

**Comment by Torakushi** [comment]
For me the increment/decrease should do the trick (+ it's thread safe)

I would prefer disconnected_node_count indeed because it is agnostic to our node count.
