### ISSUE TITLE
Add mechanism to prevent multiple instances from running in parallel

### ISSUE THREAD

**Issue by joostjager** [NYDIG-OSS/lnmux#67]
If multiple instances run in parallel and each instance subscribes to one or more lnd instances in the same cluster, things may get messy. Concurrent database writes, unexpected updates and generally not safe.

We have to add a locking mechanism so that only one instance ever runs at the same time. And we have to assume that instances run on different machines/containers, so it needs to be some form of a distributed lock.

As we already dependent on postgres, the simplest solution here might be to use a postgres advisory lock. Although not sure if that really works. It seems an advisory lock doesn't have an expiration, so maybe it is re-acquired too quickly after the first applications loses the db connection.

**Comment by joostjager** [comment]
This looks good for inspiration https://github.com/cirello-io/pglock

**Comment by joostjager** [comment]
More background on distributed locking and its challenges: https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html. Focuses on Redis, but ideas are generally applicable.

**Comment by Torakushi** [comment]
Using redis for distributed lock is a common pattern (I already used https://github.com/bsm/redislock to achieve that and that’s pretty good).
But do we really want to use a redis only for instance locking? (I know the link you provided is only an example)

For the lib you found https://github.com/cirello-io/pglock, It is simply a ForUpdate done on a particular row.
Maybe (if we want to use this kind of synchronisation) we can do it ourself? We will be free from a dependency. 

For example simply do a:

`SELECT xxxxx  FOR UPDATE SKIP LOCK` in a transaction will be safe


Little note for pg advisory lock -->  the lock can only be released **by the same connection that created the lock.** 
We must be vigilant  (we need to set the conn pool length to 1 or do a verification)

**Comment by joostjager** [comment]
Ah no, I didn't want to suggest using Redis. I just found the background info on distributed locking in that article interesting.

**Comment by Torakushi** [comment]
Yes, I understood :) 

Just, since the redis lock pattern is really common, I was wondering if we should consider it.
Although.. adding a dependency to redis may not be a good idea!

**Comment by joostjager** [comment]
Opened a similar issue for lnd: https://github.com/lightningnetwork/lnd/issues/6894

Maybe k8s support is not a bad alternative. Postgres instance locking doesn't seem to be that common really.
