### ISSUE TITLE
Remove logs in `failInvoice` for settled or cancelled invoice

### ISSUE THREAD

**Issue by Torakushi** [NYDIG-OSS/lnmux#85]
Currently, even if an invoice is settled, we will still display the log:

`logger.Debugw("Invoice to fail no longer open/accepted")` 

because the invoice is still in `autoReleaseHeap`.

It could be good to remove it from `autoReleaseHeap` or to change the log.

**Comment by Torakushi** [comment]
1) If we want to remove the invoice from autoReleaseHeap we can create a function like:

```
func (p *priorityQueue) Delete(hash string) *item {
	for i:= 0; i< p.Len(); i++{
	       if p[i].value == hash {
		   return heap.Remove(p, i).(*item)
	       }
	}
	return nil
}
```

**PLUS create a new autoReleaseHeapTick**

We need to think about synchronisation as well.


2) Otherwise we can simply check if the hash is in the DB during the `failInvoice` call [here](https://github.com/bottlepay/lnmux/blob/3a3dfbcd2fdcb06610c3d64ae796ee726ffaf524/invoiceregistry.go#L490)

**Comment by joostjager** [comment]
I think just removing the log may be the most efficient solution.

**Comment by Torakushi** [comment]
Yes, indeed it is the most efficient!
But It could be nice to indicate to the user when an invoice reach the acceptTimeout no?

**Comment by joostjager** [comment]
Isn't that already happening with `logger.Infow("Failed invoice")` ?

**Comment by Torakushi** [comment]
You're totally right
I changed the title
